# Generated by Django 4.2.3 on 2023-07-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('cpf', models.CharField(max_length=14)),
                ('trabalha_com_aftas', models.BooleanField(default=False)),
                ('trabalha_com_hipersensibilidade', models.BooleanField(default=False)),
                ('trabalha_com_lesoes', models.BooleanField(default=False)),
                ('trabalha_com_pos_cirurgia', models.BooleanField(default=False)),
                ('trabalha_com_nevralgia', models.BooleanField(default=False)),
                ('trabalha_com_consulta', models.BooleanField(default=False)),
            ],
        ),
    ]
