# Generated by Django 4.2.3 on 2023-07-20 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('medico', '0001_initial'),
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datas.data')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medico.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultas', to='paciente.paciente')),
            ],
        ),
    ]
